
name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  skip:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  build-result:
    name: Result
    runs-on: ubuntu-latest
    if: always()
    needs:
      - fail
      - ok
      - skip
    steps:
      - name: Mark the job as successful
        if: ${{ success() }}
        run: exit 0
      - name: Mark the job as unsuccessful
        if: ${{ failure() }}
        run: exit 1
